spring:
  datasource:
    url: jdbc:h2:mem:db_pgtel
    username: dev
    password: test
  jpa:
    database: H2
    show-sql: 'true'
    hibernate:
      ddl-auto: none
  database:
    driverClassName: org.h2.Driver
server:
  port: 8080

pgtel:
  app:
    jwtSecret: mySecret
    jwtExpirationMs: 86400000 # 1 day